### PR TITLE
8 dummy data

### PR DESCRIPTION
**Pull request by Markussim**

### CODE REVIEW

**Review by linusromland — CHANGES_REQUESTED** [review]
Crashes on manual change in db. (ex. delete one of the countries from the dummy data and then restarting the server)

Maybe consider not running add dummy data on main.js and instead create a package.json script to add data to prevent the error.

**Comment by Markussim** [comment]
> Crashes on manual change in db. (ex. delete one of the countries from the dummy data and then restarting the server)
> 
> Maybe consider not running add dummy data on main.js and instead create a package.json script to add data to prevent the error.

Changed to check if any data exits in DB, if it does the script does not do anything

**Review by linusromland — CHANGES_REQUESTED** [review]
Looks good!

Some improvments:
- oneliner on if statments
- Inconsitent naming scheme
- Change TMP to other name (ex. `languageTMP` could be `languageTableName` or `languageName` and a comment explaning)
- Use of name `Element` in forEach loops
- 
-

**Review by linusromland — APPROVED** [review]
Looks good now! 👍🏻

**Pull request merged**
